## import the library we need.

In [1]:
import numpy as np

<img src="graph.jpg"> 

In [2]:
graph = {
    'A': ['B', 'C', 'D', 'E'],
    'B': ['A', 'F'],
    'C': ['A', 'G'],
    'D': ['A', 'H'],
    'E': ['A', 'I'],
    'F': ['B'],
    'G': ['C', 'J'],
    'H': ['D', 'K'],
    'I': ['E', 'L'],
    'J': ['G'],
    'K': ['H'],
    'L': ['I'],
}

# (A) Form the adjacency matrix A

In [3]:
def GenerateAdjacencyMatrix(graph):
    nodes = list(graph.keys())
    n_nodes = len(nodes)
    AdjacencyMatrix = np.zeros((n_nodes, n_nodes))
    for node1_id in range(n_nodes):
        for node2_id in range(n_nodes):
            if nodes[node2_id] in graph[nodes[node1_id]]:
                AdjacencyMatrix[node1_id][node2_id] = 1
    return AdjacencyMatrix

def GenerateAdjacencyMatrix2(graph):
    nodes = list(graph.keys())
    n_nodes = len(nodes)
    AdjacencyMatrix = np.zeros((n_nodes, n_nodes))
    for node1_id in range(n_nodes):
        for node2 in graph[nodes[node1_id]]:
            node2_id = nodes.index(node2)
            node2_id = ord(node2) - ord('A')
            AdjacencyMatrix[node1_id][node2_id] = 1
    return AdjacencyMatrix

In [4]:
A = GenerateAdjacencyMatrix(graph)
print('The adjacency matrix A:')
print(A)

The adjacency matrix A:
[[0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


# (B) Form the degree matrix D

In [5]:
def GenerateDegreeMatrix(AdjacencyMatrix):
    return np.diag(np.sum(AdjacencyMatrix, axis=0))

In [6]:
D = GenerateDegreeMatrix(A)
print('The degree matrix D:')
print(D)

The degree matrix D:
[[4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# (C) From the Laplacian matrix ℒ = D − A

In [7]:
def GenerateGraphLaplacian(DegreeMatrix, AdjacencyMatrix):
    return DegreeMatrix - AdjacencyMatrix

In [8]:
ℒ = GenerateGraphLaplacian(D, A)
print('The Laplacian matrix ℒ:')
print(ℒ)

The Laplacian matrix ℒ:
[[ 4. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  2.  0.  0.  0. -1.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  2.  0.  0.  0. -1.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  2.  0.  0.  0. -1.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  2.  0.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  2.  0.  0. -1.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  2.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  1.]]


# (D) If the initial values of the nodes are
# x = {A, B, C, D, E, F, G, H, I, J, K, L} = {1,0,0,0,0,0,0,0,0,0,0,0}
# Compute ℒ ∗ x, ℒ ∗ ℒ ∗ x, ℒ ∗ ℒ ∗ ℒ ∗ x

In [9]:
x = [1] + [0] * (len(graph.keys()) - 1)

In [10]:
print('ℒ ∗ x:')
# print(np.dot(ℒ, x))
print(np.matmul(ℒ, x))

ℒ ∗ x:
[ 4. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.  0.]


In [11]:
print('ℒ ∗ ℒ ∗ x:')
print(np.matmul(np.matmul(ℒ, ℒ), x))

ℒ ∗ ℒ ∗ x:
[20. -6. -6. -6. -6.  1.  1.  1.  1.  0.  0.  0.]


In [12]:
print('ℒ ∗ ℒ ∗ ℒ ∗ x:')
print(np.dot(np.dot(ℒ, np.dot(ℒ, ℒ)), x))

ℒ ∗ ℒ ∗ ℒ ∗ x:
[104. -33. -33. -33. -33.   7.   8.   8.   8.  -1.  -1.  -1.]
